### ISSUE TITLE
Is this supposted to work?

### ISSUE THREAD

**Issue by cRaZy92** [slynn1324/BambuP1Streamer#1]
It was pretty painful to get it to actually run...
But after that, all I got was error `mjpeg: EOF`

![image](https://github.com/slynn1324/BambuP1Streamer/assets/33964772/d947a8e8-8b0d-4a2e-9c5b-a72eece46ada)

Do you have any tips?

**Comment by slynn1324** [comment]
Sorry for the slow response -- it's working here... but that's admittedly a very small sample size.   There could be lots of things giving you issues here... not sure where to point you specifically based on what you've shared here.
