### ISSUE TITLE
Can we get a tutorial?

### ISSUE THREAD

**Issue by mon5termatt** [slynn1324/BambuP1Streamer#3]
I can't for the life of me get this set up. And I use docker a TON

**Comment by mon5termatt** [comment]
Where am i supposed to extract this to. it looks like its hard-coded to /work but a lot of other stuff doesn't line up.

**Comment by 459below** [comment]
@mon5termatt

PR #7 is ready and working.
I assume the maintainer is busy.

@slynn1324,

Thank you for sharing your code. As a long-time Debian user, I value your approach. I'm migrating my Docker stacks to Podman and plan to write the [Quadlet](https://www.redhat.com/sysadmin/quadlet-podman) for BambuP1Streamer next. After completion, I'll submit another PR.

**Comment by 459below** [comment]
Oh and the visual reassurance that I got this actually working with those commands:

![Screenshot from 2024-03-09 16-17-05](https://github.com/slynn1324/BambuP1Streamer/assets/11325631/c5cfde6e-add1-4535-9fb8-97e2a5afc018)
